import express, { Request, Response, NextFunction } from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { extractVideoId, getTranscript } from './youtube';
import { generateTimestampsWithAI } from './openai';
import { validateTimestamps } from './validator';
import type { VideoRequest, TimestampResponse } from './types';

// Load environment variables
dotenv.config();

const app = express();
const PORT = process.env.PORT || 8000;

// Middleware
app.use(cors());
app.use(express.json());

// Health check endpoints
app.get('/healthz', (_req: Request, res: Response) => {
  res.json({ status: 'ok' });
});

app.get('/api/health', (_req: Request, res: Response) => {
  res.json({ status: 'ok' });
});

// Main endpoint to generate timestamps
app.post('/api/generate', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { url, language = 'pt', min_segment_duration = 30 } = req.body as VideoRequest;

    // Validate request
    if (!url) {
      res.status(400).json({ detail: 'URL é obrigatória' });
      return;
    }

    // Extract video ID
    const videoId = extractVideoId(url);
    if (!videoId) {
      res.status(400).json({ detail: 'URL do YouTube inválida' });
      return;
    }

    // Check for OpenAI API key
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      res.status(500).json({ detail: 'OPENAI_API_KEY não configurada' });
      return;
    }

    // Get transcript
    const transcript = await getTranscript(videoId, language);

    // Generate timestamps with AI
    const aiResult = await generateTimestampsWithAI(
      transcript,
      min_segment_duration,
      apiKey
    );

    // Validate timestamps
    const validated = validateTimestamps(
      aiResult.timestamps || [],
      transcript,
      0.7,
      min_segment_duration
    );

    // Build response
    const response: TimestampResponse = {
      timestamps: validated,
      metadata: {
        video_id: videoId,
        language: transcript.language,
        is_auto_generated: transcript.isAutoGenerated,
        total_candidates: aiResult.timestamps?.length || 0,
        validated_count: validated.length,
      },
    };

    res.json(response);
  } catch (error) {
    next(error);
  }
});

// Error handling middleware
app.use((err: Error, _req: Request, res: Response, _next: NextFunction) => {
  console.error('Error:', err.message);
  res.status(500).json({ detail: err.message || 'Erro interno do servidor' });
});

// Start server
app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});
