import express, { Request, Response, NextFunction } from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { extractVideoId, getTranscript } from './youtube';
import { generateTimestampsWithAI } from './openai';
import { validateTimestamps } from './validator';
import { getCacheStats, clearOldCache, deleteCacheForVideo } from './cache';
import type { VideoRequest, TimestampResponse } from './types';
import { 
  AppError, 
  createInvalidVideoIdError, 
  createMissingAPIKeyError 
} from './errors';
import { VALIDATION_CONFIG } from './validation-config';

// Load environment variables
dotenv.config();

const app = express();
const PORT = process.env.PORT || 8000;

// Increase timeout for long videos (10 minutes)
const TIMEOUT_MS = 10 * 60 * 1000; // 10 minutes

// Middleware
app.use(cors());
app.use(express.json());

// Set timeout for all requests
app.use((req, res, next) => {
  req.setTimeout(TIMEOUT_MS);
  res.setTimeout(TIMEOUT_MS);
  next();
});

// Health check endpoints
app.get('/healthz', (_req: Request, res: Response) => {
  res.json({ status: 'ok' });
});

app.get('/api/health', (_req: Request, res: Response) => {
  res.json({ status: 'ok' });
});

// Cache statistics endpoint
app.get('/api/cache/stats', (_req: Request, res: Response) => {
  const stats = getCacheStats();
  res.json(stats);
});

// Clear old cache endpoint
app.post('/api/cache/clear', (_req: Request, res: Response) => {
  clearOldCache();
  res.json({ message: 'Cache cleared successfully' });
});

// Delete cache for specific video
app.delete('/api/cache/:videoId', (req: Request, res: Response) => {
  const { videoId } = req.params;
  const { language = 'pt' } = req.query;
  const deleted = deleteCacheForVideo(videoId, language as string);
  res.json({ 
    message: deleted ? 'Cache deleted successfully' : 'Cache not found',
    deleted 
  });
});

// Endpoint to get transcript only (without AI timestamp generation)
app.post('/api/transcript', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { url, language = 'pt', force_whisper } = req.body as VideoRequest;

    // Validate request
    if (!url) {
      throw new AppError({
        code: 'INVALID_URL' as any,
        message: 'URL is required',
        userMessage: 'URL é obrigatória',
        suggestions: ['Forneça uma URL válida do YouTube'],
        httpStatus: 400,
      });
    }

    // Extract video ID
    const videoId = extractVideoId(url);
    if (!videoId) {
      throw createInvalidVideoIdError();
    }

    // Check for OpenAI API key (needed for Whisper fallback)
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey || apiKey === 'your_openai_api_key_here') {
      throw createMissingAPIKeyError();
    }

    // Get transcript (with Whisper fallback if no subtitles or low coverage)
    const { 
      transcript, 
      fromCache, 
      videoTitle, 
      videoDuration, 
      transcriptCoverage, 
      whisperReason 
    } = await getTranscript(videoId, language, true, apiKey, force_whisper);

    // Return transcript with metadata
    res.json({
      transcript: {
        video_id: transcript.videoId,
        video_title: videoTitle,
        language: transcript.language,
        segments: transcript.segments,
        is_auto_generated: transcript.isAutoGenerated,
      },
      metadata: {
        video_id: videoId,
        video_title: videoTitle,
        language: transcript.language,
        is_auto_generated: transcript.isAutoGenerated,
        used_speech_to_text: !transcript.isAutoGenerated,
        whisper_reason: whisperReason,
        from_cache: fromCache,
        total_segments: transcript.segments.length,
        transcript_coverage: transcriptCoverage,
        video_duration: videoDuration,
      },
    });
  } catch (error) {
    next(error);
  }
});

// Main endpoint to generate timestamps
app.post('/api/generate', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { url, language = 'pt', min_segment_duration = 30, force_whisper } = req.body as VideoRequest;

    // Validate request
    if (!url) {
      throw new AppError({
        code: 'INVALID_URL' as any,
        message: 'URL is required',
        userMessage: 'URL é obrigatória',
        suggestions: ['Forneça uma URL válida do YouTube'],
        httpStatus: 400,
      });
    }

    // Extract video ID
    const videoId = extractVideoId(url);
    if (!videoId) {
      throw createInvalidVideoIdError();
    }

    // Check for OpenAI API key
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey || apiKey === 'your_openai_api_key_here') {
      throw createMissingAPIKeyError();
    }

    // Get transcript (with Whisper fallback if no subtitles or low coverage)
    const { 
      transcript, 
      fromCache, 
      videoTitle, 
      videoDuration, 
      transcriptCoverage, 
      whisperReason 
    } = await getTranscript(videoId, language, true, apiKey, force_whisper);

    // Generate timestamps with AI
    const aiResult = await generateTimestampsWithAI(
      transcript,
      min_segment_duration,
      apiKey,
      videoTitle
    );

    // Validate timestamps using centralized config
    const validated = validateTimestamps(
      aiResult.timestamps || [],
      transcript,
      VALIDATION_CONFIG.DEFAULT_MIN_CONFIDENCE,
      min_segment_duration
    );

    // Build response
    const response: TimestampResponse = {
      timestamps: validated,
      metadata: {
        video_id: videoId,
        language: transcript.language,
        is_auto_generated: transcript.isAutoGenerated,
        used_speech_to_text: !transcript.isAutoGenerated, // Whisper sets isAutoGenerated to false
        whisper_reason: whisperReason,
        from_cache: fromCache,
        total_candidates: aiResult.timestamps?.length || 0,
        validated_count: validated.length,
        transcript_coverage: transcriptCoverage,
        video_duration: videoDuration,
      },
    };

    res.json(response);
  } catch (error) {
    next(error);
  }
});

// Error handling middleware
app.use((err: Error | AppError, _req: Request, res: Response, _next: NextFunction) => {
  // Log error for debugging
  console.error('Error occurred:', {
    name: err.name,
    message: err.message,
    ...(err instanceof AppError ? { code: err.code, suggestions: err.suggestions } : {}),
  });

  // If it's our custom AppError, return structured error
  if (err instanceof AppError) {
    return res.status(err.httpStatus).json(err.toJSON());
  }

  // Generic error fallback
  res.status(500).json({
    error: {
      code: 'UNKNOWN_ERROR',
      message: 'Erro interno do servidor',
      suggestions: ['Tente novamente mais tarde', 'Se o erro persistir, entre em contato com o suporte'],
    },
  });
});

// Start server
app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});
