/**
 * Local Whisper Integration
 * 
 * This module provides integration with the local faster-whisper Python server
 * for speech-to-text transcription without requiring any paid APIs.
 */

import fs from 'fs';
import path from 'path';
import FormData from 'form-data';
import axios from 'axios';
import type { Transcript, TranscriptSegment } from './types';
import { AppError } from './errors';
import { downloadYouTubeAudio } from './audio-ytdlp';
import { getCachedTranscript, cacheTranscript } from './cache';
import { VALIDATION_CONFIG } from './validation-config';

// Default local Whisper server URL
const WHISPER_SERVER_URL = process.env.WHISPER_SERVER_URL || 'http://localhost:5000';

const TEMP_DIR = path.join(process.cwd(), 'temp');

// Ensure temp directory exists
if (!fs.existsSync(TEMP_DIR)) {
  fs.mkdirSync(TEMP_DIR, { recursive: true });
}

/**
 * Check if the local Whisper server is running
 */
export async function checkWhisperServerHealth(): Promise<boolean> {
  try {
    const response = await axios.get(`${WHISPER_SERVER_URL}/health`, {
      timeout: 5000
    });
    return response.data?.status === 'ok' && response.data?.model_loaded === true;
  } catch {
    return false;
  }
}

/**
 * Get information about the local Whisper server
 */
export async function getWhisperServerInfo(): Promise<{
  status: string;
  model: string;
  modelLoaded: boolean;
} | null> {
  try {
    const response = await axios.get(`${WHISPER_SERVER_URL}/health`, {
      timeout: 5000
    });
    return {
      status: response.data?.status || 'unknown',
      model: response.data?.model || 'unknown',
      modelLoaded: response.data?.model_loaded || false
    };
  } catch {
    return null;
  }
}

/**
 * Transcribe audio using the local Whisper server
 */
export async function transcribeWithLocalWhisper(
  audioPath: string,
  language: string = 'pt'
): Promise<Transcript> {
  // Check if server is running
  const isHealthy = await checkWhisperServerHealth();
  if (!isHealthy) {
    throw new AppError({
      code: 'WHISPER_SERVER_UNAVAILABLE' as any,
      message: 'Local Whisper server is not running',
      userMessage: 'Servidor Whisper local não está rodando',
      suggestions: [
        'Inicie o servidor Whisper: cd backend/local-whisper && python server.py',
        'Verifique se o Python e faster-whisper estão instalados',
        'Verifique se a porta 5000 está disponível'
      ],
      httpStatus: 503
    });
  }

  try {
    // Get file info
    const stats = fs.statSync(audioPath);
    const fileSizeMB = Math.round(stats.size / 1024 / 1024 * 10) / 10;
    console.log(`[LocalWhisper] Audio file size: ${fileSizeMB}MB`);

    // Create form data with the audio file
    const formData = new FormData();
    formData.append('file', fs.createReadStream(audioPath));
    formData.append('language', language === 'auto' ? '' : language);

    console.log(`[LocalWhisper] Sending audio to local Whisper server...`);
    const startTime = Date.now();

    // Send to local Whisper server
    const response = await axios.post(
      `${WHISPER_SERVER_URL}/transcribe`,
      formData,
      {
        headers: formData.getHeaders(),
        timeout: 600000, // 10 minutes timeout for long videos
        maxContentLength: Infinity,
        maxBodyLength: Infinity
      }
    );

    const elapsed = Math.round((Date.now() - startTime) / 1000);
    console.log(`[LocalWhisper] Transcription completed in ${elapsed} seconds`);

    const data = response.data;
    console.log(`[LocalWhisper] Detected language: ${data.language}`);
    console.log(`[LocalWhisper] Total segments: ${data.segments?.length || 0}`);

    // Convert response to our Transcript format
    const segments: TranscriptSegment[] = (data.segments || []).map((seg: any) => ({
      text: seg.text,
      offset: seg.start,
      duration: seg.end - seg.start
    }));

    const transcript: Transcript = {
      videoId: path.basename(audioPath, path.extname(audioPath)),
      language: data.language || language,
      segments,
      isAutoGenerated: false // Local Whisper transcriptions are not auto-generated
    };

    console.log(`[LocalWhisper] Returning transcript with ${segments.length} segments`);
    return transcript;

  } catch (error: any) {
    console.error(`[LocalWhisper] Transcription error:`, error.message);
    
    if (error.code === 'ECONNREFUSED') {
      throw new AppError({
        code: 'WHISPER_SERVER_UNAVAILABLE' as any,
        message: 'Cannot connect to local Whisper server',
        userMessage: 'Não foi possível conectar ao servidor Whisper local',
        suggestions: [
          'Inicie o servidor: cd backend/local-whisper && python server.py',
          'Verifique se a porta 5000 está disponível'
        ],
        httpStatus: 503
      });
    }

    throw error;
  }
}

/**
 * Main function to get transcript using local Whisper
 * This is called when YouTube subtitles are not available
 */
export async function getTranscriptWithLocalWhisper(
  videoId: string,
  language: string = 'pt'
): Promise<Transcript> {
  // Check cache first
  const cached = getCachedTranscript(videoId, language);
  if (cached) {
    console.log(`[LocalWhisper] Using cached transcript for ${videoId}`);
    return cached.transcript;
  }

  let audioPath: string | null = null;

  try {
    // Step 1: Download audio from YouTube
    console.log(`\n[LocalWhisper] STEP 1/3: Downloading audio for video ${videoId}...`);
    audioPath = await downloadYouTubeAudio(videoId, VALIDATION_CONFIG.MAX_VIDEO_DURATION);
    console.log(`[LocalWhisper] Audio downloaded successfully to ${audioPath}`);

    // Step 2: Transcribe with local Whisper
    console.log(`\n[LocalWhisper] STEP 2/3: Transcribing audio with local Whisper...`);
    const transcript = await transcribeWithLocalWhisper(audioPath, language);

    // Step 3: Process and cache
    console.log(`\n[LocalWhisper] STEP 3/3: Processing and caching transcript...`);

    // Update videoId to match the input
    transcript.videoId = videoId;

    // Cache the transcript
    cacheTranscript(videoId, language, transcript, 'whisper');

    console.log(`[LocalWhisper] All steps completed successfully!`);
    return transcript;

  } catch (error: any) {
    console.error(`[LocalWhisper] Process failed:`, error.message);
    throw error;
  } finally {
    // Clean up temporary audio file
    if (audioPath && fs.existsSync(audioPath)) {
      fs.unlinkSync(audioPath);
    }
  }
}
