export interface TranscriptSegment {
  text: string;
  offset: number;
  duration: number;
}

export interface Transcript {
  videoId: string;
  language: string;
  segments: TranscriptSegment[];
  isAutoGenerated: boolean;
}

export interface TimestampCandidate {
  time: number;
  title: string;
  confidence: number;
  evidence: string;
}

export interface GenerationMetadata {
  video_id: string;
  language: string;
  is_auto_generated: boolean;
  used_speech_to_text?: boolean;
  from_cache?: boolean;
  total_candidates: number;
  validated_count: number;
}

export interface TimestampResponse {
  timestamps: TimestampCandidate[];
  metadata: GenerationMetadata;
}

export interface VideoRequest {
  url: string;
  language?: string;
  min_segment_duration?: number;
}
