/**
 * Type definitions for the YouTube Timestamp Generator.
 * 
 * Time Representation:
 * - All time values are stored as floating-point seconds from the beginning of the video
 * - YouTube API returns milliseconds, which are converted to seconds during processing
 * - Whisper API returns seconds directly
 * - For display, times are floored to the nearest second and formatted as MM:SS or HH:MM:SS
 */

/**
 * A segment of transcript text with timing information.
 * Represents a single caption/subtitle segment from the video.
 * 
 * @property text - The transcript text content for this segment
 * @property offset - Start time in seconds from beginning of video
 * @property duration - Duration of this segment in seconds
 */
export interface TranscriptSegment {
  text: string;
  offset: number;
  duration: number;
}

/**
 * Complete transcript for a video.
 * Contains all segments and metadata about the transcript source.
 * 
 * @property videoId - YouTube video ID
 * @property language - Language code of the transcript (e.g., 'pt', 'en', 'es', 'auto')
 * @property segments - Array of transcript segments with timing
 * @property isAutoGenerated - Whether the transcript was auto-generated (YouTube) or from Whisper
 */
export interface Transcript {
  videoId: string;
  language: string;
  segments: TranscriptSegment[];
  isAutoGenerated: boolean;
}

/**
 * A timestamp candidate generated by AI analysis.
 * Represents a potential chapter marker for the video.
 * 
 * @property time - Start time in seconds from beginning of video
 * @property title - Short descriptive title for this chapter (typically 3-8 words)
 * @property confidence - AI confidence score for this timestamp (0.0 to 1.0)
 * @property evidence - Transcript text that supports/justifies this timestamp
 */
export interface TimestampCandidate {
  time: number;
  title: string;
  confidence: number;
  evidence: string;
}

/**
 * Metadata about the timestamp generation process.
 * Provides transparency about how timestamps were generated.
 * 
 * @property video_id - YouTube video ID that was processed
 * @property language - Language of the transcript used
 * @property is_auto_generated - Whether YouTube auto-generated subtitles were used
 * @property used_speech_to_text - Whether Whisper speech-to-text was used (fallback)
 * @property whisper_reason - Reason why Whisper was used (if applicable)
 * @property from_cache - Whether the transcript was retrieved from cache
 * @property total_candidates - Number of timestamps generated by AI before validation
 * @property validated_count - Number of timestamps that passed validation
 * @property transcript_coverage - Ratio of transcript duration to video duration (0.0 to 1.0)
 * @property video_duration - Total video duration in seconds
 */
export interface GenerationMetadata {
  video_id: string;
  language: string;
  is_auto_generated: boolean;
  used_speech_to_text?: boolean;
  whisper_reason?: 'no_subtitles' | 'low_coverage' | 'force_whisper';
  from_cache?: boolean;
  total_candidates: number;
  validated_count: number;
  transcript_coverage?: number;
  video_duration?: number;
}

/**
 * Complete API response for timestamp generation.
 * Contains validated timestamps and generation metadata.
 * 
 * @property timestamps - Array of validated timestamp candidates
 * @property metadata - Information about the generation process
 */
export interface TimestampResponse {
  timestamps: TimestampCandidate[];
  metadata: GenerationMetadata;
}

/**
 * Request payload for the /api/generate endpoint.
 * 
 * @property url - YouTube video URL to process
 * @property language - Preferred language for transcript (default: 'pt')
 * @property min_segment_duration - Minimum seconds between timestamps (default: 30)
 * @property force_whisper - Force use of Whisper even if subtitles exist
 */
export interface VideoRequest {
  url: string;
  language?: string;
  min_segment_duration?: number;
  force_whisper?: boolean;
}
