import type { Transcript, TimestampCandidate } from './types';

/**
 * Validate timestamps generated by AI
 * Implements multiple layers of anti-hallucination validation
 */
export function validateTimestamps(
  timestamps: TimestampCandidate[],
  transcript: Transcript,
  minConfidence: number = 0.7,
  minDuration: number = 30
): TimestampCandidate[] {
  const validated: TimestampCandidate[] = [];
  let lastTime = -minDuration;

  // Calculate total duration
  const lastSegment = transcript.segments[transcript.segments.length - 1];
  const totalDuration = lastSegment
    ? lastSegment.offset + lastSegment.duration
    : 0;

  for (const ts of timestamps) {
    // Validation 1: Minimum confidence
    if ((ts.confidence ?? 0) < minConfidence) {
      continue;
    }

    // Validation 2: Timestamp is within video duration
    if (ts.time < 0 || ts.time > totalDuration) {
      continue;
    }

    // Validation 3: Minimum spacing
    if (ts.time - lastTime < minDuration) {
      continue;
    }

    // Validation 4: Title is not empty
    if (!ts.title?.trim()) {
      continue;
    }

    validated.push(ts);
    lastTime = ts.time;
  }

  // Add initial timestamp if not present
  if (validated.length === 0 || validated[0].time > 10) {
    const firstSegment = transcript.segments[0];
    validated.unshift({
      time: 0,
      title: 'Introdução',
      confidence: 1.0,
      evidence: firstSegment?.text ?? '',
    });
  }

  // Sort by time
  validated.sort((a, b) => a.time - b.time);

  return validated;
}
