import { YoutubeTranscript } from 'youtube-transcript';
import type { Transcript, TranscriptSegment } from './types';

/**
 * Extract video ID from YouTube URL
 */
export function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/)([^&\n?#]+)/,
    /youtube\.com\/embed\/([^&\n?#]+)/,
    /youtube\.com\/v\/([^&\n?#]+)/,
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) {
      return match[1];
    }
  }

  return null;
}

/**
 * Get transcript from YouTube video
 */
export async function getTranscript(
  videoId: string,
  preferredLanguage: string = 'pt'
): Promise<Transcript> {
  try {
    // Try to fetch transcript with preferred language
    const transcriptItems = await YoutubeTranscript.fetchTranscript(videoId, {
      lang: preferredLanguage,
    });

    const segments: TranscriptSegment[] = transcriptItems.map((item) => ({
      text: item.text,
      offset: item.offset / 1000, // Convert to seconds
      duration: item.duration / 1000, // Convert to seconds
    }));

    return {
      videoId,
      language: preferredLanguage,
      segments,
      isAutoGenerated: true, // youtube-transcript doesn't distinguish
    };
  } catch (error) {
    // Try English as fallback
    if (preferredLanguage !== 'en') {
      try {
        const transcriptItems = await YoutubeTranscript.fetchTranscript(videoId, {
          lang: 'en',
        });

        const segments: TranscriptSegment[] = transcriptItems.map((item) => ({
          text: item.text,
          offset: item.offset / 1000,
          duration: item.duration / 1000,
        }));

        return {
          videoId,
          language: 'en',
          segments,
          isAutoGenerated: true,
        };
      } catch {
        // Fall through to error
      }
    }

    // Try without language specification
    try {
      const transcriptItems = await YoutubeTranscript.fetchTranscript(videoId);

      const segments: TranscriptSegment[] = transcriptItems.map((item) => ({
        text: item.text,
        offset: item.offset / 1000,
        duration: item.duration / 1000,
      }));

      return {
        videoId,
        language: 'auto',
        segments,
        isAutoGenerated: true,
      };
    } catch {
      throw new Error(
        `Não foi possível obter a transcrição do vídeo. Verifique se o vídeo possui legendas disponíveis.`
      );
    }
  }
}

/**
 * Format timestamp from seconds to MM:SS or HH:MM:SS
 */
export function formatTimestamp(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);

  if (hours > 0) {
    return `${hours}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  }
  return `${minutes}:${secs.toString().padStart(2, '0')}`;
}

/**
 * Format transcript for AI processing
 */
export function formatTranscriptForAI(segments: TranscriptSegment[]): string {
  return segments
    .map((segment) => `[${formatTimestamp(segment.offset)}] ${segment.text.trim()}`)
    .join('\n');
}
