"""
Exporter Module - Saves transcript and timestamps to local files
"""

import json
import os
from typing import List

from .transcriber import Transcript, format_time
from .timestamp_generator import Timestamp


def export_transcript(
    transcript: Transcript,
    output_path: str,
    include_timestamps: bool = True
) -> str:
    """
    Export transcript to a text file with granular timestamps.
    
    Args:
        transcript: Transcript object
        output_path: Path to output file
        include_timestamps: Whether to include timestamps in output
        
    Returns:
        Path to created file
    """
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    
    lines = []
    lines.append("=" * 60)
    lines.append("TRANSCRIÇÃO COMPLETA")
    lines.append(f"Idioma: {transcript.language}")
    lines.append(f"Duração Total: {format_time(transcript.duration)}")
    lines.append(f"Total de Segmentos: {len(transcript.segments)}")
    lines.append("=" * 60)
    lines.append("")
    
    if include_timestamps:
        for i, segment in enumerate(transcript.segments, 1):
            start_str = format_time(segment.start)
            end_str = format_time(segment.end)
            # Formato: [00:00 - 00:15] Texto da fala
            lines.append(f"[{start_str} - {end_str}] {segment.text}")
    else:
        lines.append(transcript.full_text)
    
    lines.append("")
    lines.append("=" * 60)
    
    content = "\n".join(lines)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"[Exporter] Saved transcript to: {output_path}")
    return output_path


def export_transcript_json(
    transcript: Transcript,
    output_path: str,
    video_title: str = "",
    video_id: str = ""
) -> str:
    """
    Export full transcript with all segments to JSON (granular timestamps).
    
    Args:
        transcript: Transcript object
        output_path: Path to output file
        video_title: Optional video title
        video_id: Optional video ID
        
    Returns:
        Path to created file
    """
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    
    data = {
        "video_title": video_title,
        "video_id": video_id,
        "language": transcript.language,
        "duration": transcript.duration,
        "duration_formatted": format_time(transcript.duration),
        "segment_count": len(transcript.segments),
        "segments": [
            {
                "index": i,
                "start": segment.start,
                "end": segment.end,
                "start_formatted": format_time(segment.start),
                "end_formatted": format_time(segment.end),
                "duration": round(segment.end - segment.start, 2),
                "text": segment.text
            }
            for i, segment in enumerate(transcript.segments)
        ],
        "full_text": transcript.full_text
    }
    
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    
    print(f"[Exporter] Saved transcript (json) to: {output_path}")
    return output_path


def export_timestamps_txt(
    timestamps: List[Timestamp],
    output_path: str,
    video_title: str = ""
) -> str:
    """
    Export timestamps to a text file in YouTube description format.
    
    Args:
        timestamps: List of Timestamp objects
        output_path: Path to output file
        video_title: Optional video title for header
        
    Returns:
        Path to created file
    """
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    
    lines = []
    
    if video_title:
        lines.append(f"Timestamps for: {video_title}")
        lines.append("")
    
    lines.append("TIMESTAMPS (Copy to YouTube description):")
    lines.append("-" * 40)
    
    for ts in timestamps:
        time_str = format_time(ts.time)
        lines.append(f"{time_str} - {ts.title}")
    
    lines.append("-" * 40)
    lines.append("")
    lines.append("Generated by YouTube Timestamp Generator")
    
    content = "\n".join(lines)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"[Exporter] Saved timestamps (txt) to: {output_path}")
    return output_path


def export_timestamps_json(
    timestamps: List[Timestamp],
    output_path: str,
    video_title: str = "",
    video_id: str = ""
) -> str:
    """
    Export timestamps to a JSON file.
    
    Args:
        timestamps: List of Timestamp objects
        output_path: Path to output file
        video_title: Optional video title
        video_id: Optional video ID
        
    Returns:
        Path to created file
    """
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    
    data = {
        "video_title": video_title,
        "video_id": video_id,
        "timestamp_count": len(timestamps),
        "timestamps": [
            {
                "time": ts.time,
                "formatted": format_time(ts.time),
                "title": ts.title,
                "confidence": ts.confidence
            }
            for ts in timestamps
        ]
    }
    
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    
    print(f"[Exporter] Saved timestamps (json) to: {output_path}")
    return output_path


def export_all(
    transcript: Transcript,
    timestamps: List[Timestamp],
    output_dir: str,
    video_id: str,
    video_title: str
) -> dict:
    """
    Export all outputs:
    - Transcrição completa (TXT) com timestamps granulares [início - fim]
    - Transcrição completa (JSON) com todos os segmentos detalhados
    - Timestamps por tópicos (TXT) para descrição do YouTube
    - Timestamps por tópicos (JSON) estruturado
    
    Args:
        transcript: Transcript object
        timestamps: List of Timestamp objects
        output_dir: Output directory
        video_id: Video ID for filenames
        video_title: Video title for headers
        
    Returns:
        Dictionary with paths to all created files
    """
    os.makedirs(output_dir, exist_ok=True)
    
    # Create safe filename prefix
    safe_id = video_id[:20] if video_id else "video"
    
    paths = {}
    
    # 1. Export transcript (TXT) - transcrição granular com [início - fim]
    transcript_path = os.path.join(output_dir, f"{safe_id}_transcript.txt")
    paths['transcript_txt'] = export_transcript(transcript, transcript_path)
    
    # 2. Export transcript (JSON) - todos os segmentos com timestamps detalhados
    transcript_json_path = os.path.join(output_dir, f"{safe_id}_transcript.json")
    paths['transcript_json'] = export_transcript_json(transcript, transcript_json_path, video_title, video_id)
    
    # 3. Export timestamps/tópicos (TXT) - formato para YouTube
    timestamps_txt_path = os.path.join(output_dir, f"{safe_id}_timestamps.txt")
    paths['timestamps_txt'] = export_timestamps_txt(timestamps, timestamps_txt_path, video_title)
    
    # 4. Export timestamps/tópicos (JSON) - estruturado
    timestamps_json_path = os.path.join(output_dir, f"{safe_id}_timestamps.json")
    paths['timestamps_json'] = export_timestamps_json(timestamps, timestamps_json_path, video_title, video_id)
    
    return paths


if __name__ == "__main__":
    # Test the exporter
    from .transcriber import TranscriptSegment
    
    # Create test data
    test_transcript = Transcript(
        language="en",
        segments=[
            TranscriptSegment(start=0, end=10, text="Hello and welcome"),
            TranscriptSegment(start=10, end=20, text="Today we discuss Python"),
        ],
        full_text="Hello and welcome. Today we discuss Python.",
        duration=120
    )
    
    test_timestamps = [
        Timestamp(time=0, title="Introduction"),
        Timestamp(time=60, title="Main Topic"),
    ]
    
    paths = export_all(
        test_transcript,
        test_timestamps,
        "./test_output",
        "test123",
        "Test Video"
    )
    
    print(f"Created files: {paths}")
